apiVersion: v1
kind: Service
metadata: 
  name: phpapp-svc
spec:
  selector:
    matchLabels:
       labels:
         app: phpapp
    ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
    type: LoadBalancer
