kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects: 
- kind: User # this can be Group as well
  name: "rohit.kamle@silicus.com" # user id can also be added here
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # this can be role or ClusterRole
  name: pod-reader # must match the role name
  apiGroup: rbac.authorization.k8s.io
